version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: innoneti_test    # نام دیتابیس
      MYSQL_USER: innoneti_test         # نام کاربری دیتابیس
      MYSQL_PASSWORD: test@dmin987654321         # پسورد کاربر دیتابیس
    ports:
      - "3306:3306"  # پورت دیتابیس رو باز می‌کنیم تا بتونید از بیرون بهش دسترسی داشته باشید
    volumes:
      - mariadb_data:/var/lib/mysql   # ذخیره داده‌ها در Volume

  web:
    build: .   # از Dockerfile پروژه برای ساخت تصویر استفاده می‌کنیم
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # کد پروژه رو داخل کانتینر می‌ریزیم
    ports:
      - "8000:8000"  # پورت جنگو رو باز می‌کنیم
    depends_on:
      - db   # این خط میگه که کانتینر وب باید بعد از کانتینر دیتابیس بالا بیاد
    environment:
      DATABASE_HOST: db  # در اینجا "db" نام سرویس دیتابیس هست که در این فایل تعریف شده
      DATABASE_PORT: 3306
      DATABASE_NAME: innoneti_test
      DATABASE_USER: innoneti_test
      DATABASE_PASSWORD: test@dmin987654321

volumes:
  mariadb_data:
