# Generated by Django 5.1.6 on 2025-02-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registrationNumber', models.CharField(max_length=100)),
                ('nationalID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesAndMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandIdentity', models.IntegerField()),
                ('visualIdentityActivities', models.IntegerField()),
                ('brandReputationManagement', models.IntegerField()),
                ('brandTrustAndEmotionalConnection', models.IntegerField()),
                ('marketResearchOpportunities', models.IntegerField()),
                ('salesToIndustryRatio', models.IntegerField()),
                ('marketLeadershipPotential', models.IntegerField()),
                ('orderDeliveryTimeliness', models.IntegerField()),
                ('salesNetworkCoverage', models.IntegerField()),
                ('salesAgencySupervision', models.IntegerField()),
                ('salesRepProductAwareness', models.IntegerField()),
                ('reliableTransportUsage', models.IntegerField()),
                ('digitalMarketingUsage', models.IntegerField()),
                ('marketResearchForMarketing', models.IntegerField()),
                ('marketingPlanningAndGuidelines', models.IntegerField()),
                ('marketingAndSalesNetworking', models.IntegerField()),
                ('innovativeMarketingUsage', models.IntegerField()),
                ('exhibitionParticipation', models.IntegerField()),
                ('salesAmountToCostRatio', models.IntegerField()),
                ('salesGrowthLast3Months', models.IntegerField()),
                ('salesToProductionRatio', models.IntegerField()),
                ('targetMarketDefinition', models.IntegerField()),
                ('marketRegulationsKnowledge', models.IntegerField()),
                ('competitorAwareness', models.IntegerField()),
                ('exportActivitiesAndGlobalMarketUse', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
    ]
