# Generated by Django 5.2 on 2025-04-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areze_yab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='icon',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='descriptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('OE', 'Open Ended')], default='MC', max_length=2),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
