# Generated by Django 5.1.6 on 2025-02-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areze_yab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_financing_reliability', models.IntegerField()),
                ('availability_of_funds_for_new_projects', models.IntegerField()),
                ('company_risk_tolerance_for_investments', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRelationshipManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_purchase_information_documentation', models.IntegerField()),
                ('customer_feedback_registration_system', models.IntegerField()),
                ('customer_feedback_analysis', models.IntegerField()),
                ('special_sales_plans_for_loyal_customers', models.IntegerField()),
                ('payment_benefits_for_loyal_customers', models.IntegerField()),
                ('first_purchase_support_plan', models.IntegerField()),
                ('employee_training_for_customer_service', models.IntegerField()),
                ('number_of_loyal_customers', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_cash_flow_maintenance', models.IntegerField()),
                ('ability_to_fulfill_financial_commitments', models.IntegerField()),
                ('available_assets_for_short_term_liabilities', models.IntegerField()),
                ('weekly_monthly_annual_burn_rate', models.IntegerField()),
                ('organizational_profitability_efficiency', models.IntegerField()),
                ('ability_to_pay_suppliers_and_creditors', models.IntegerField()),
                ('total_processing_cost_of_payments_invoices', models.IntegerField()),
                ('total_financial_activity_cost_ratio', models.IntegerField()),
                ('accuracy_and_completeness_of_financial_reports', models.IntegerField()),
                ('difference_between_forecasted_and_actual_budget', models.IntegerField()),
                ('change_in_total_sales_over_a_period', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
        migrations.CreateModel(
            name='HumanResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workforce_efficiency', models.IntegerField()),
                ('daily_work_backlog', models.IntegerField()),
                ('available_staff_for_new_projects', models.IntegerField()),
                ('staff_with_5_years_experience', models.IntegerField()),
                ('employee_satisfaction', models.IntegerField()),
                ('employee_job_change_request', models.IntegerField()),
                ('early_retirement_requests', models.IntegerField()),
                ('organizational_support', models.IntegerField()),
                ('annual_salary_adjustment', models.IntegerField()),
                ('manager_satisfaction_with_staff', models.IntegerField()),
                ('staff_satisfaction_with_manager', models.IntegerField()),
                ('revenue_per_employee', models.IntegerField()),
                ('employee_responsibility_and_commitment', models.IntegerField()),
                ('performance_evaluation_planning', models.IntegerField()),
                ('performance_evaluation_technology', models.IntegerField()),
                ('evaluation_criteria_job_alignment', models.IntegerField()),
                ('practical_staff_grading_system', models.IntegerField()),
                ('internal_training_programs', models.IntegerField()),
                ('support_for_external_training', models.IntegerField()),
                ('managerial_focus_on_teamwork', models.IntegerField()),
                ('staff_interest_in_teamwork', models.IntegerField()),
                ('shared_workspace_availability', models.IntegerField()),
                ('regular_weekly_meetings', models.IntegerField()),
                ('management_staff_interaction', models.IntegerField()),
                ('respect_for_employee_privacy', models.IntegerField()),
                ('gender_equality_in_management', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementOrganizationalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprehensive_and_clear_org_chart', models.IntegerField()),
                ('regular_org_chart_updates', models.IntegerField()),
                ('existence_of_information_management_system', models.IntegerField()),
                ('integrated_knowledge_management_across_units', models.IntegerField()),
                ('workspace_design', models.IntegerField()),
                ('implementation_of_5s_methodology', models.IntegerField()),
                ('defined_mission_and_vision_statements', models.IntegerField()),
                ('employee_awareness_of_organizational_plans', models.IntegerField()),
                ('organizational_efforts_for_customer_awareness', models.IntegerField()),
                ('employee_decision_making_power', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCompetitiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinctive_product_features', models.IntegerField()),
                ('product_quality_compared_to_competitors', models.IntegerField()),
                ('brand_positioning_in_market', models.IntegerField()),
                ('responsiveness_to_market_needs', models.IntegerField()),
                ('product_adaptability_to_customer_preferences', models.IntegerField()),
                ('production_cost_efficiency', models.IntegerField()),
                ('pricing_competitiveness', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAndDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existence_of_rnd_department', models.IntegerField()),
                ('rnd_department_responsibilities_clarity', models.IntegerField()),
                ('rnd_production_collaboration', models.IntegerField()),
                ('budget_allocation_for_rnd', models.IntegerField()),
                ('organizational_innovation_planning', models.IntegerField()),
                ('structured_innovation_process', models.IntegerField()),
                ('use_of_customer_feedback_and_market_analysis', models.IntegerField()),
                ('organizational_innovation_culture', models.IntegerField()),
                ('unique_product_features', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company')),
            ],
        ),
    ]
