# Generated by Django 5.1.6 on 2025-03-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areze_yab', '0003_rename_availability_of_funds_for_new_projects_capitalstructure_availability_of_resources_for_new_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcompetitiveness',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitalstructure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
        migrations.AlterField(
            model_name='customerrelationshipmanagement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
        migrations.AlterField(
            model_name='financialresources',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
        migrations.AlterField(
            model_name='humanresources',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
        migrations.AlterField(
            model_name='managementorganizationalstructure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
        migrations.AlterField(
            model_name='manufacturingandproduction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
        migrations.AlterField(
            model_name='researchanddevelopment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
        migrations.AlterField(
            model_name='salesandmarketing',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
    ]
