# Generated by Django 5.1.6 on 2025-03-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areze_yab', '0006_alter_capitalstructure_availability_of_resources_for_new_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
