# Generated by Django 5.1.7 on 2025-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areze_yab', '0011_remove_customuser_nationalid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='capitalstructure',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerrelationshipmanagement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='financialresources',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='humanresources',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='managementorganizationalstructure',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manufacturingandproduction',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcompetitiveness',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchanddevelopment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesandmarketing',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
