# Generated by Django 5.1.7 on 2025-03-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areze_yab', '0012_rename_company_name_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesandmarketing',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
        ),
    ]
