# Generated by Django 5.1.7 on 2025-03-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areze_yab', '0013_alter_salesandmarketing_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesandmarketing',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='areze_yab.company'),
            preserve_default=False,
        ),
    ]
